language: android
sudo: true
git:
  depth: 5
addons:
  sauce_connect: true
before_script:
  - nvm install $(< .nvmrc)
  - npm config set user 0
  - npm config set unsafe-perm true
script:
  - npm run build
  - npm run cordova:build android
  - npm run test-ci
branches:
  only:
    - master
deploy:
  - provider: heroku
    skip_cleanup: true
    api_key:
        secure: iGMpfoFCBzSKKpDCOHQEjm/PFRbnIV81M0q7/i95xg32xsMGcsBfYH0QXeNk0b1UTsBoZ6r+CWX38F214/YHMrI4bT//3wxrQ7S0AjGJbdPcgGrEwrjofbI1/AqrCmd96PuqxHspoqlkMnugzm7JdIINbkklL5XJJK5A9rGQoOh7N3Y3VEcNOwHrOeI4BeGgVo7ZVqiKgWFeLs5r9/CGdtNeWYBcq0HGh8UssdBVX8VVzhSUDaXzbtLq0aWd/1v9WnRZ9wovinGaey2YmE8WWW/NY+oqFxxPrJXUPy+UnQGA26Z/DQDrUnuO4uEtVTN8x6AI7yC2azvaNBnNfBZjMk72GuAUPYDxvHBjXpXxdTI1jpfoXWcEFepsR1U0X7MKcecfMMMhIMlqfvvkybHjpyP1ucM3TOhWIn6obyf9Ll0oPCE4zRR/OxcYifSpO1WP9zoUbkiGczcBQGIq4QFjD37qwYCXvXkehawB3PLErlPojJsRwHE1DJxAHV9DIHxSQ1A2d7W0LNu6Jz94z5YidMuytw3XDxZwYJZWO6zqm9R0UUxXm+uTQXCEgRgcNjFUdDJVR1D56zkhZi/2XcYfO1aXQhkcicIJkpTew/luNMBy8X5+9gIhbuoQbTDPxA/mHeyrJ3hj5LPzSY0rbShArfTJYpgyN7uvu1ZZ/tuwCOo=
after_deploy:
  - npm run protractor
cache:
  directories:
    - node_modules