language: node_js
sudo: false
git:
  depth: 5
addons:
  sauce_connect: true
before_install:
  - npm install -g npm@latest
script:
  - npm run build
  - npm run test-ci
  - npm run protractor
branches:
  only:
    - master
deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: kIjGaonxh4AF5Jg1kZgdGEBDPUZbk8MB4Ofp5K0LPbOK8zeI/wjAalp5uETLvVGSX8kl/bAhdLSjFefVDH5pZl5Y9xQSEITA8HX46JAe3Be1XNXeNvx7Ti6Qm0CxKiLpA+FALfH5aED0qInBctIOh/ggN5sF1jtSVbF+reto6NjMP89F9aRyEcQvJlmRjEsPph2WD/qGpsbvDxGeZEFOOtciLV+5uLkAbVFJdLS2BvLjJRX24GTP3KZItIH5qoA7w4FLhw1J9IhkBNnM/7eBRKMS82NCOEa0OlXDN3CuFop9ey9XdvRzDEj7NLC7BxWfGzlQ0qEksbfyiE8mEN0pgq8Y7OfipKDBSRdrxd6HXhbQ5/7TuHxgAxw2fR5FFkA3qIbMPEnbRDJ7KgCn7GH95fgozq31OSFiQQ1NgaVmtNGDa4kqlSI9afmUDy7kPoupQzrO3bHjf+Fc9PRQNi0Hgr0RfSofMdc7RFJDoBXEUbKvc8IQqtdgpWiQWybh1kO/JLNlSYJU5oXRDQfBKv0+DV/ZjKlTod0gT7illMfD2Os+LViXOtEfXvfXNaSN9NS72zxMlbHlvvQqDj4168di909sEXLHgweAIdzOHHEh7TMZBbosrM3rVGSbT1R6XmDVA+ewdqBmKxyrMIzpBKMXJbJTp5Okka9xX7lqKjbvytQ=
cache:
  directories:
    - node_modules
