language: node_js
sudo: true
node_js:
  - "5"
git:
  depth: 5
addons:
  sauce_connect: true
before_install:
 - sudo apt-get install openjdk-7-jdk
 - sudo apt-get update
 - sudo apt-get install -qq libstdc++6:i386 lib32z1 expect
 - cat android-sdk-installer | bash /dev/stdin --install=build-tools-23.1.0,android-23,sys-img-armeabi-v7a-android-23
 - set COMPONENTS="build-tools-23.1.0,android-23,sysimg-23"
 - set LICENSES="android-sdk-license-5be876d5|mips-android-sysimage-license-15de68cc|intel-android-sysimage-license-1ea702d1"
 - curl -L https://raw.github.com/embarkmobile/android-sdk-installer/version-2/android-sdk-installer | bash /dev/stdin --install=$COMPONENTS --accept=$LICENSES && source ~/.android-sdk-installer/env
 - update sdk --no-ui --all --filter build-tools" "android-sdk-license-5be876d5|mips-android-sysimage-license-15de68cc"
 - ls -la
 - source ~/.android-sdk-installer/env
script:
  - npm run version
  - npm run build
  - npm run copy
  - npm run cordova:prepare
  - npm run cordova:build:android
  - npm run test-ci
branches:
  only:
    - master
deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: iGMpfoFCBzSKKpDCOHQEjm/PFRbnIV81M0q7/i95xg32xsMGcsBfYH0QXeNk0b1UTsBoZ6r+CWX38F214/YHMrI4bT//3wxrQ7S0AjGJbdPcgGrEwrjofbI1/AqrCmd96PuqxHspoqlkMnugzm7JdIINbkklL5XJJK5A9rGQoOh7N3Y3VEcNOwHrOeI4BeGgVo7ZVqiKgWFeLs5r9/CGdtNeWYBcq0HGh8UssdBVX8VVzhSUDaXzbtLq0aWd/1v9WnRZ9wovinGaey2YmE8WWW/NY+oqFxxPrJXUPy+UnQGA26Z/DQDrUnuO4uEtVTN8x6AI7yC2azvaNBnNfBZjMk72GuAUPYDxvHBjXpXxdTI1jpfoXWcEFepsR1U0X7MKcecfMMMhIMlqfvvkybHjpyP1ucM3TOhWIn6obyf9Ll0oPCE4zRR/OxcYifSpO1WP9zoUbkiGczcBQGIq4QFjD37qwYCXvXkehawB3PLErlPojJsRwHE1DJxAHV9DIHxSQ1A2d7W0LNu6Jz94z5YidMuytw3XDxZwYJZWO6zqm9R0UUxXm+uTQXCEgRgcNjFUdDJVR1D56zkhZi/2XcYfO1aXQhkcicIJkpTew/luNMBy8X5+9gIhbuoQbTDPxA/mHeyrJ3hj5LPzSY0rbShArfTJYpgyN7uvu1ZZ/tuwCOo=
after_deploy:
  - npm run protractor
cache:
  directories:
    - node_modules
